{
  "openapi": "3.0.0",
  "site_name": "Noebs docs",
  "info": {
    "title": "Noebs API Docs",
    "description": "# Introduction\n\nNoebs is a middleware that consumes EBS services. It was built to be simple, developer friendly and customizable enough to be used\nin different scenarios and adapt to variety of different logics.\n\n# Overview\nWe make great use of http status codes; it is one of our design decisions. We believe that they make client codes more easy and it helps us too to make a robust API.\nYou only get 200 on successful transactions.\nYou get 400 in case of missing a field, or using wron types\nYou get 502 in EBS payment gateway errors (e.g., insufficient fund)\n\n# Authentication\nWhat is the preferred way of using the API?\n\n# Error Codes\nWe use different kind of error codes:\n- 400 for validations errors (e.g., missing a required field)\n- 502 for EBS (payment gateway) errors (e.g., when you have an insufficient balance)\n- 504 for EBS (payment gateway) timeouts. E.g., EBS server is unreachable\n\n",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://beta.soluspay.net",
      "variables": {},
      "description": "Live noebs payment server"
    }
  ],
  "paths": {
    "/workingKey": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "working Key request fields",
        "description": "Working key is the key used by EBS for card holder's info encryption",
        "operationId": "WorkingKeyAPI",
        "requestBody": {
          "description": "Working key is the key used by EBS for card holder's info encryption",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "clientId",
                  "systemTraceAuditNumber",
                  "tranDateTime",
                  "terminalId"
                ],
                "properties": {
                  "clientId": {
                    "type": "string",
                    "format": "string",
                    "description": "fuck me i hate this"
                  },
                  "systemTraceAuditNumber": {
                    "type": "integer",
                    "format": "int32",
                    "description": "auto increment integer value for each transaction"
                  },
                  "tranDateTime": {
                    "type": "string",
                    "format": "string",
                    "description": "transaction date time in YYMMddhhmmss format"
                  },
                  "terminalId": {
                    "type": "string",
                    "format": "string"
                  }
                }
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response (only successful responses result in status code of 200",
            "headers": { "content-type": "application/json" }
          }
        },
        "deprecated": false
      }
    },
    "/purchase": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Purchase API",
        "description": "Purchase API for merchants purchases",
        "operationId": "PurchaseAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PurchaseAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "ebs_response": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Approval",
                    "responseStatus": "Successful",
                    "responseCode": 0,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cardTransfer": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Card Transfer API",
        "description": "Funds transfer API",
        "operationId": "CardTransferAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CardTransferAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/balance": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Balance API",
        "description": "Get balance of the user's card API",
        "operationId": "BalanceAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BalanceAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/changePin": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Change PIN API",
        "description": "Change a user's PIN",
        "operationId": "ChangePINAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePINAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "newPIN": "3233222222222222"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1cardTransfer"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/isAlive": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Is Alive API",
        "description": "Returns the stats of EBS payment gateway",
        "operationId": "IsAliveAPI",
        "requestBody": {
          "description": "Request parameters for is alive",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IsAliveAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request parameters for is alive",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IsAliveAPIRequest"
                }
              }
            },
            "deprecated": false
          }
        }
      }
    },
    "/v1/key": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Online Payment Key (Consumer)",
        "description": "This API is used to get public key to be used in encryption",
        "operationId": "OnlineKeyAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/OnlineKeyAPI"
              },
              "example": {
                "applicationId": "provider-application-id",
                "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
                "tranDateTime": "200419085611"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 601,
                  "status": "EBSError",
                  "details": {
                      "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
                      "responseMessage": "INVALID_APPLICATION_ID",
                      "responseStatus": "Failed",
                      "responseCode": 601,
                      "tranDateTime": "200222113700"
                  }
              }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/v1/purchase": {
      "post": {
        "tags": ["EBS Fields"],
        "summary": "Online Purchase",
        "description": "This API is used for online transactions",
        "operationId": "OnlinePurchaseAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/OnlinePaymentAPI"
              },
              "example": {
                "applicationId": "ACTS",
                "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
                "tranDateTime": "200419085611",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "IPIN": "encrypted-ipin-block-here",
                "tranAmount": 950,
                "tranCurrency": "SDG",
                "serviceProviderId": "your-merchant-id-here"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 601,
                  "status": "EBSError",
                  "details": {
                      "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
                      "responseMessage": "INVALID_APPLICATION_ID",
                      "responseStatus": "Failed",
                      "responseCode": 601,
                      "tranDateTime": "200222113700"
                  }
              }
              }
            }
          }
        },
        "deprecated": false
      }
    }

    
  },
  "components": {
    "schemas": {
      "workingKey": {
        "title": "Working Key Request Fields",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string",
            "format": "string",
            "example": "ACTS"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32",
            "description": "auto increment integer value for each transaction"
          },
          "tranDateTime": {
            "type": "string",
            "format": "string",
            "description": "transaction date time in YYMMddhhmmss format"
          },
          "terminalId": {
            "type": "string",
            "format": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377"
        }
      },
      "PurchaseAPIRequest": {
        "title": "PurchaseAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG"
        }
      },
      "CardTransferAPIRequest": {
        "title": "CardTransferAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      },
      "BalanceAPIRequest": {
        "title": "BalanceAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      },
      "ChangePINAPIRequest": {
        "title": "ChangePINAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "newPIN"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "newPIN": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "newPIN": "3233222222222222"
        }
      },
      "IsAliveAPIRequest": {
        "title": "IsAliveAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      },
      "OnlineKeyAPI": {
        "title": "Get Public Key API",
        "required": [
          "applicationId",
          "UUID",
          "tranDateTime",
        ],
        "type": "object",
        "properties": {
          "applicationId": {
            "type": "string"
          },
          "UUID": {
            "type": "string"
           
          },
          "tranDateTime": {
            "type": "string"
          }
         
        },
        "example": {
          "clientId": "provider-keys",
          "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
          "tranDateTime": "200419085611"
        }
      },
      "OnlinePaymentAPI": {
        "title": "Online Purchase API",
        "required": [
          "applicationId",
          "UUID",
          "tranDateTime",
          "serviceProviderId",
          "PAN",
          "expDate",
          "IPIN",
          "tranAmount",
          "tranCurrency"
        ],
        "type": "object",
        "properties": {
          "applicationId": {
            "type": "string"
          },
          "UUID": {
            "type": "string"
           
          },
          "tranDateTime": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "IPIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrency": {
            "type": "string"
          },
          "serviceProviderId": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "provider-keys",
          "UUID": "4a6ef7c4-ddfa-42bb-b555-7971e955c01a",
          "tranDateTime": "200419085611",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "encrypted-ipin-block-here",
          "tranAmount": 950,
          "tranCurrency": "SDG",
          "serviceProviderId": "your-merchant-id-here"
        }
      }
    },
    "securitySchemes": {
      "httpBasic": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "tags": [
    {
      "name": "EBS Fields",
      "description": "Testing EBS fields output"
    }
  ]
}
