openapi: 3.0.0
info:
  title: Noebs -- Merchant APIs
  description: |-
    Test me

    We really care about you and your fucking software
  contact:
    name: Mohamed Yousif
    email: mmbusif@gmail.com
  version: "1.0"
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
  termsOfService: "https://soluspay.net/privacy"
servers:
  - url: "https://beta.soluspay.net/api"
    variables: {}
    description: Live noebs payment server
paths:
  /workingKey:
    post:
      tags:
        - temp
      summary: working Key request fields
      description: Working key is the key used by EBS for card holder's info encryption
      operationId: WorkingKeyAPI
      requestBody:
        description: Working key is the key used by EBS for card holder's info encryption
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
                - systemTraceAuditNumber
                - tranDateTime
                - terminalId
              properties:
                clientId:
                  type: string
                  format: string
                  description: fuck me i hate this
                systemTraceAuditNumber:
                  type: integer
                  format: int32
                  description: auto increment integer value for each transaction
                tranDateTime:
                  type: string
                  format: string
                  description: transaction date time in YYMMddhhmmss format
                terminalId:
                  type: string
                  format: string
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
        required: true
      responses:
        "200":
          description: >-
            Successful Response (only successful responses result in status code
            of 200
          headers:
            content-type: application/json
      deprecated: false
      parameters: []
  /purchase:
    post:
      tags:
        - EBS Fields
      summary: Purchase API
      description: Purchase API for merchants purchases
      operationId: PurchaseAPI
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseAPIRequest"
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
              PAN: "6392560017624665"
              expDate: "2303"
              PIN: 221eb901ed3b40b1
              tranAmount: 950
              tranCurrencyCode: SDG
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance
              example:
                ebs_response:
                  terminalId: "18000377"
                  systemTraceAuditNumber: 54
                  clientId: ACTS
                  PAN: "4665"
                  responseMessage: Approval
                  responseStatus: Successful
                  responseCode: 0
                  tranDateTime: "200419085611"
                  tranFee: 0
                  additionalAmount: -1
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance
              example:
                message: EBSError
                code: 194
                status: EBSError
                details:
                  terminalId: "18000377"
                  systemTraceAuditNumber: 54
                  clientId: ACTS
                  PAN: "4665"
                  responseMessage: Duplicate transaction
                  responseStatus: Failed
                  responseCode: 194
                  tranDateTime: "200419085611"
                  tranFee: 0
                  additionalAmount: -1
      deprecated: false
  /cardTransfer:
    post:
      tags:
        - EBS Fields
      summary: Card Transfer API
      description: Funds transfer API
      operationId: CardTransferAPI
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardTransferAPIRequest"
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
              PAN: "6392560017624665"
              expDate: "2303"
              PIN: 221eb901ed3b40b1
              tranAmount: 950
              tranCurrencyCode: SDG
              toCard: "6391871100137098"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance
              example:
                message: EBSError
                code: 194
                status: EBSError
                details:
                  terminalId: "18000377"
                  systemTraceAuditNumber: 54
                  clientId: ACTS
                  PAN: "4665"
                  responseMessage: Duplicate transaction
                  responseStatus: Failed
                  responseCode: 194
                  tranDateTime: "200419085611"
                  tranFee: 0
                  additionalAmount: -1
      deprecated: false
  /balance:
    post:
      tags:
        - EBS Fields
      summary: Balance API
      description: Get balance of the user's card API
      operationId: BalanceAPI
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceAPIRequest"
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
              PAN: "6392560017624665"
              expDate: "2303"
              PIN: 221eb901ed3b40b1
              tranAmount: 950
              tranCurrencyCode: SDG
              toCard: "6391871100137098"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance
              example:
                message: EBSError
                code: 194
                status: EBSError
                details:
                  terminalId: "18000377"
                  systemTraceAuditNumber: 54
                  clientId: ACTS
                  PAN: "4665"
                  responseMessage: Duplicate transaction
                  responseStatus: Failed
                  responseCode: 194
                  tranDateTime: "200419085611"
                  tranFee: 0
                  additionalAmount: -1
      deprecated: false
  /changePin:
    post:
      tags:
        - EBS Fields
      summary: Change PIN API
      description: Change a user's PIN
      operationId: ChangePINAPI
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePINAPIRequest"
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
              PAN: "6392560017624665"
              expDate: "2303"
              PIN: 221eb901ed3b40b1
              newPIN: "3233222222222222"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/https%3A~1~1beta.soluspay.net~1api~1cardTransfer
              example:
                message: EBSError
                code: 194
                status: EBSError
                details:
                  terminalId: "18000377"
                  systemTraceAuditNumber: 54
                  clientId: ACTS
                  PAN: "4665"
                  responseMessage: Duplicate transaction
                  responseStatus: Failed
                  responseCode: 194
                  tranDateTime: "200419085611"
                  tranFee: 0
      deprecated: false
  /isAlive:
    post:
      tags:
        - EBS Fields
      summary: Is Alive API
      description: Returns the stats of EBS payment gateway
      operationId: IsAliveAPI
      requestBody:
        description: Request parameters for is alive
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IsAliveAPIRequest"
            example:
              clientId: ACTS
              systemTraceAuditNumber: 54
              tranDateTime: "200419085611"
              terminalId: "18000377"
              PAN: "6392560017624665"
              expDate: "2303"
              PIN: 221eb901ed3b40b1
              tranAmount: 950
              tranCurrencyCode: SDG
              toCard: "6391871100137098"
        required: true
      responses:
        "200":
          description: Request parameters for is alive
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IsAliveAPIRequest"
          deprecated: false
      parameters: []
components:
  schemas:
    workingKey:
      title: Working Key Request Fields
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
      type: object
      properties:
        clientId:
          type: string
          format: string
          example: ACTS
        systemTraceAuditNumber:
          type: integer
          format: int32
          description: auto increment integer value for each transaction
        tranDateTime:
          type: string
          format: string
          description: transaction date time in YYMMddhhmmss format
        terminalId:
          type: string
          format: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
    PurchaseAPIRequest:
      title: PurchaseAPIRequest
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
        - PAN
        - expDate
        - PIN
        - tranAmount
        - tranCurrencyCode
      type: object
      properties:
        clientId:
          type: string
        systemTraceAuditNumber:
          type: integer
          format: int32
        tranDateTime:
          type: string
        terminalId:
          type: string
        PAN:
          type: string
        expDate:
          type: string
        PIN:
          type: string
        tranAmount:
          type: integer
          format: int32
        tranCurrencyCode:
          type: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
        PAN: "6392560017624665"
        expDate: "2303"
        PIN: 221eb901ed3b40b1
        tranAmount: 950
        tranCurrencyCode: SDG
    CardTransferAPIRequest:
      title: CardTransferAPIRequest
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
        - PAN
        - expDate
        - PIN
        - tranAmount
        - tranCurrencyCode
        - toCard
      type: object
      properties:
        clientId:
          type: string
        systemTraceAuditNumber:
          type: integer
          format: int32
        tranDateTime:
          type: string
        terminalId:
          type: string
        PAN:
          type: string
        expDate:
          type: string
        PIN:
          type: string
        tranAmount:
          type: integer
          format: int32
        tranCurrencyCode:
          type: string
        toCard:
          type: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
        PAN: "6392560017624665"
        expDate: "2303"
        PIN: 221eb901ed3b40b1
        tranAmount: 950
        tranCurrencyCode: SDG
        toCard: "6391871100137098"
    BalanceAPIRequest:
      title: BalanceAPIRequest
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
        - PAN
        - expDate
        - PIN
        - tranAmount
        - tranCurrencyCode
        - toCard
      type: object
      properties:
        clientId:
          type: string
        systemTraceAuditNumber:
          type: integer
          format: int32
        tranDateTime:
          type: string
        terminalId:
          type: string
        PAN:
          type: string
        expDate:
          type: string
        PIN:
          type: string
        tranAmount:
          type: integer
          format: int32
        tranCurrencyCode:
          type: string
        toCard:
          type: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
        PAN: "6392560017624665"
        expDate: "2303"
        PIN: 221eb901ed3b40b1
        tranAmount: 950
        tranCurrencyCode: SDG
        toCard: "6391871100137098"
    ChangePINAPIRequest:
      title: ChangePINAPIRequest
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
        - PAN
        - expDate
        - PIN
        - newPIN
      type: object
      properties:
        clientId:
          type: string
        systemTraceAuditNumber:
          type: integer
          format: int32
        tranDateTime:
          type: string
        terminalId:
          type: string
        PAN:
          type: string
        expDate:
          type: string
        PIN:
          type: string
        newPIN:
          type: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
        PAN: "6392560017624665"
        expDate: "2303"
        PIN: 221eb901ed3b40b1
        newPIN: "3233222222222222"
    IsAliveAPIRequest:
      title: IsAliveAPIRequest
      required:
        - clientId
        - systemTraceAuditNumber
        - tranDateTime
        - terminalId
        - PAN
        - expDate
        - PIN
        - tranAmount
        - tranCurrencyCode
        - toCard
      type: object
      properties:
        clientId:
          type: string
        systemTraceAuditNumber:
          type: integer
          format: int32
        tranDateTime:
          type: string
        terminalId:
          type: string
        PAN:
          type: string
        expDate:
          type: string
        PIN:
          type: string
        tranAmount:
          type: integer
          format: int32
        tranCurrencyCode:
          type: string
        toCard:
          type: string
      example:
        clientId: ACTS
        systemTraceAuditNumber: 54
        tranDateTime: "200419085611"
        terminalId: "18000377"
        PAN: "6392560017624665"
        expDate: "2303"
        PIN: 221eb901ed3b40b1
        tranAmount: 950
        tranCurrencyCode: SDG
        toCard: "6391871100137098"
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
    newSecurityScheme:
      type: apiKey
      name: api_key
      in: query
tags:
  - name: EBS Fields
    description: ""
  - name: Pin Calculation
    description: How to calculate PIN block for encryption
security: []
