{
  "openapi": "3.0.0",
  "info": {
    "title": "Noebs -- Merchant APIs",
    "description": "# Introduction\nNoebs is a middleware that consumes EBS services. It was built to be simple, developer friendly and customizable enough to be used\nin different scenarios and adapt to variety of different logics.\n\n# Overview\nWe make great use of http status codes; it is one of our design decisions. We believe that they make client codes more easy and it helps us too to make a robust API.\nYou only get 200 on successful transactions.\nYou get 400 in case of missing a field, or using wron types\nYou get 502 in EBS payment gateway errors (e.g., insufficient fund)\n\n# Authentication\nWhat is the preferred way of using the API?\n\n# Error Codes\nWe use different kind of error codes:\n- 400 for validations errors (e.g., missing a required field)\n- 502 for EBS (payment gateway) errors (e.g., when you have an insufficient balance)\n- 504 for EBS (payment gateway) timeouts. E.g., EBS server is unreachable\n\n",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://beta.soluspay.net/api",
      "variables": {}
    }
  ],
  "paths": {
    "/api/workingKey": {
      "post": {
        "summary": "Working Key API",
        "description": "Working key is the key used by EBS for card holder's info encryption",
        "operationId": "WorkingKeyAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/WorkingKeyAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/apipurchase": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Purchase API",
        "description": "Purchase API for merchants purchases",
        "operationId": "PurchaseAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PurchaseAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/api/cardTransfer": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Card Transfer API",
        "description": "Funds transfer API",
        "operationId": "CardTransferAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CardTransferAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/api/balance": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Balance API",
        "description": "Get balance of the user's card API",
        "operationId": "BalanceAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BalanceAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1balance"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0,
                    "additionalAmount": -1
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/api/changePin": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Change PIN API",
        "description": "Change a user's PIN",
        "operationId": "ChangePINAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePINAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "newPIN": "3233222222222222"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          },
          "502": {
            "description": "Bad Gateway",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/https%3A~1~1beta.soluspay.net~1api~1cardTransfer"
                },
                "example": {
                  "message": "EBSError",
                  "code": 194,
                  "status": "EBSError",
                  "details": {
                    "terminalId": "18000377",
                    "systemTraceAuditNumber": 54,
                    "clientId": "ACTS",
                    "PAN": "4665",
                    "responseMessage": "Duplicate transaction",
                    "responseStatus": "Failed",
                    "responseCode": 194,
                    "tranDateTime": "200419085611",
                    "tranFee": 0
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/api/isAlive": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Is Alive API",
        "description": "Returns the stats of EBS payment gateway",
        "operationId": "IsAliveAPI",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IsAliveAPIRequest"
              },
              "example": {
                "clientId": "ACTS",
                "systemTraceAuditNumber": 54,
                "tranDateTime": "200419085611",
                "terminalId": "18000377",
                "PAN": "6392560017624665",
                "expDate": "2303",
                "PIN": "221eb901ed3b40b1",
                "tranAmount": 950,
                "tranCurrencyCode": "SDG",
                "toCard": "6391871100137098"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "All successful responses have this form",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "WorkingKeyAPIRequest": {
        "title": "WorkingKeyAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId"
        ],
        "type": "object",
        "properties": {

          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377"
        }
      },
      "PurchaseAPIRequest": {
        "title": "PurchaseAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG"
        }
      },
      "https://beta.soluspay.net/api/balance": {
        "title": "https://beta.soluspay.net/api/balance",
        "required": [
          "message",
          "code",
          "status",
          "details"
        ],
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "status": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/Details"
          }
        },
        "example": {
          "message": "EBSError",
          "code": 194,
          "status": "EBSError",
          "details": {
            "terminalId": "18000377",
            "systemTraceAuditNumber": 54,
            "clientId": "ACTS",
            "PAN": "4665",
            "responseMessage": "Duplicate transaction",
            "responseStatus": "Failed",
            "responseCode": 194,
            "tranDateTime": "200419085611",
            "tranFee": 0,
            "additionalAmount": -1
          }
        }
      },
      "Details": {
        "title": "Details",
        "required": [
          "terminalId",
          "systemTraceAuditNumber",
          "clientId",
          "PAN",
          "responseMessage",
          "responseStatus",
          "responseCode",
          "tranDateTime",
          "tranFee",
          "additionalAmount"
        ],
        "type": "object",
        "properties": {
          "terminalId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "clientId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "responseMessage": {
            "type": "string"
          },
          "responseStatus": {
            "type": "string"
          },
          "responseCode": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "tranFee": {
            "type": "integer",
            "format": "int32"
          },
          "additionalAmount": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "terminalId": "18000377",
          "systemTraceAuditNumber": 54,
          "clientId": "ACTS",
          "PAN": "4665",
          "responseMessage": "Duplicate transaction",
          "responseStatus": "Failed",
          "responseCode": 194,
          "tranDateTime": "200419085611",
          "tranFee": 0,
          "additionalAmount": -1
        }
      },
      "CardTransferAPIRequest": {
        "title": "CardTransferAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      },
      "BalanceAPIRequest": {
        "title": "BalanceAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      },
      "ChangePINAPIRequest": {
        "title": "ChangePINAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "newPIN"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "newPIN": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "newPIN": "3233222222222222"
        }
      },
      "https://beta.soluspay.net/api/cardTransfer": {
        "title": "https://beta.soluspay.net/api/cardTransfer",
        "required": [
          "message",
          "code",
          "status",
          "details"
        ],
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "status": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/Details3"
          }
        },
        "example": {
          "message": "EBSError",
          "code": 194,
          "status": "EBSError",
          "details": {
            "terminalId": "18000377",
            "systemTraceAuditNumber": 54,
            "clientId": "ACTS",
            "PAN": "4665",
            "responseMessage": "Duplicate transaction",
            "responseStatus": "Failed",
            "responseCode": 194,
            "tranDateTime": "200419085611",
            "tranFee": 0
          }
        }
      },
      "Details3": {
        "title": "Details3",
        "required": [
          "terminalId",
          "systemTraceAuditNumber",
          "clientId",
          "PAN",
          "responseMessage",
          "responseStatus",
          "responseCode",
          "tranDateTime",
          "tranFee"
        ],
        "type": "object",
        "properties": {
          "terminalId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "clientId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "responseMessage": {
            "type": "string"
          },
          "responseStatus": {
            "type": "string"
          },
          "responseCode": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "tranFee": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "terminalId": "18000377",
          "systemTraceAuditNumber": 54,
          "clientId": "ACTS",
          "PAN": "4665",
          "responseMessage": "Duplicate transaction",
          "responseStatus": "Failed",
          "responseCode": 194,
          "tranDateTime": "200419085611",
          "tranFee": 0
        }
      },
      "IsAliveAPIRequest": {
        "title": "IsAliveAPIRequest",
        "required": [
          "clientId",
          "systemTraceAuditNumber",
          "tranDateTime",
          "terminalId",
          "PAN",
          "expDate",
          "PIN",
          "tranAmount",
          "tranCurrencyCode",
          "toCard"
        ],
        "type": "object",
        "properties": {
          "clientId": {
            "type": "string"
          },
          "systemTraceAuditNumber": {
            "type": "integer",
            "format": "int32"
          },
          "tranDateTime": {
            "type": "string"
          },
          "terminalId": {
            "type": "string"
          },
          "PAN": {
            "type": "string"
          },
          "expDate": {
            "type": "string"
          },
          "PIN": {
            "type": "string"
          },
          "tranAmount": {
            "type": "integer",
            "format": "int32"
          },
          "tranCurrencyCode": {
            "type": "string"
          },
          "toCard": {
            "type": "string"
          }
        },
        "example": {
          "clientId": "ACTS",
          "systemTraceAuditNumber": 54,
          "tranDateTime": "200419085611",
          "terminalId": "18000377",
          "PAN": "6392560017624665",
          "expDate": "2303",
          "PIN": "221eb901ed3b40b1",
          "tranAmount": 950,
          "tranCurrencyCode": "SDG",
          "toCard": "6391871100137098"
        }
      }
    },
    "securitySchemes": {
      "httpBasic": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "httpBasic": []
    }
  ],
  "tags": [
    {
      "name": "Noebs APIs",
      "description": "Noebs APIs"
    }
  ]
}